/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AttemptAttemptIdRouteImport } from './routes/attempt.$attemptId'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems.$problemId'
import { Route as AttemptAttemptIdFeedbackRouteImport } from './routes/attempt_.$attemptId.feedback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptAttemptIdRoute = AttemptAttemptIdRouteImport.update({
  id: '/attempt/$attemptId',
  path: '/attempt/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/problems/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptAttemptIdFeedbackRoute =
  AttemptAttemptIdFeedbackRouteImport.update({
    id: '/attempt_/$attemptId/feedback',
    path: '/attempt/$attemptId/feedback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/attempt/$attemptId/feedback': typeof AttemptAttemptIdFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/attempt/$attemptId/feedback': typeof AttemptAttemptIdFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/attempt_/$attemptId/feedback': typeof AttemptAttemptIdFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/attempt/$attemptId'
    | '/problems/$problemId'
    | '/attempt/$attemptId/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/attempt/$attemptId'
    | '/problems/$problemId'
    | '/attempt/$attemptId/feedback'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/attempt/$attemptId'
    | '/problems/$problemId'
    | '/attempt_/$attemptId/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  AttemptAttemptIdRoute: typeof AttemptAttemptIdRoute
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  AttemptAttemptIdFeedbackRoute: typeof AttemptAttemptIdFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempt/$attemptId': {
      id: '/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AttemptAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempt_/$attemptId/feedback': {
      id: '/attempt_/$attemptId/feedback'
      path: '/attempt/$attemptId/feedback'
      fullPath: '/attempt/$attemptId/feedback'
      preLoaderRoute: typeof AttemptAttemptIdFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  AttemptAttemptIdRoute: AttemptAttemptIdRoute,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  AttemptAttemptIdFeedbackRoute: AttemptAttemptIdFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
